# Generated by Django 3.1.5 on 2021-01-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poet', '0005_auto_20210117_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(default='', max_length=200),
        ),
    ]
