# Generated by Django 3.1.5 on 2021-01-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poet', '0006_auto_20210117_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='', max_length=200),
        ),
    ]
